import { type BlogPost, h2, p } from './types.js';

const post: BlogPost = {
  slug: 'anchor-peers-and-subnet-diversity',
  title: 'Anchor Peers and Subnet Diversity: Staying Connected Across Restarts',
  date: '2026-06-02',
  tags: ['technical', 'engineering', 'bitcoin'],
  excerpt: 'A node that forgets its peers on every restart is slow to rejoin the network. QubitCoin persists the most recently seen peers as anchors and enforces /16 subnet diversity when picking outbound connections &mdash; two simple mechanisms that make bootstrapping faster and eclipse attacks harder.',
  content: () => `<h1 class="text-2xl font-bold mb-2">Anchor Peers and Subnet Diversity: Staying Connected Across Restarts</h1>
<p class="text-text-muted text-xs font-mono mb-8">2026-06-02</p>
${p('A fresh node that just started has no connections and no memory of who it talked to last time. Its only lifeline is a hard-coded seed list. That works, but it is slow and puts a lot of trust in a small set of well-known addresses. Bitcoin solved this problem years ago with two complementary ideas: persist recently-seen peers so they survive restarts, and enforce address diversity when picking outbound connections so one operator cannot saturate your peer slots from a single network range. QubitCoin implements both.')}
${h2('Anchor Peers')}
${p('Every time the P2P server runs its discovery loop, it writes a snapshot of the ten most recently active known addresses to <span class="font-mono text-xs text-qubit-400">anchors.json</span> in the node&rsquo;s data directory. On the next startup, those addresses are loaded back into the in-memory address book before any seeds are dialled:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">const data = fs.readFileSync(this.anchorsPath, \'utf-8\')<br>const anchors: unknown = JSON.parse(data)<br>if (!Array.isArray(anchors)) return<br>for (const a of anchors) {<br>&nbsp;&nbsp;const parsed = this.parseAddressEntry(a)<br>&nbsp;&nbsp;if (parsed) this.upsertKnownAddress(parsed.host, parsed.port, parsed.lastSeen, false)<br>}</span>')}
${p('The <span class="font-mono text-xs text-qubit-400">false</span> flag on <span class="font-mono text-xs text-qubit-400">upsertKnownAddress</span> is the important part: it skips the routability filter. Normally the server rejects private and link-local addresses so that local test nodes do not leak into the public address book. For anchors that check is bypassed, because these entries were already validated when they were first seen &mdash; the node trusts its own past observation more than it trusts a routability heuristic. Each loaded entry is still validated against the expected schema; malformed entries log a warning and are skipped rather than crashing the load.')}
${p('Once the anchors are in the address book the server calls <span class="font-mono text-xs text-qubit-400">connectToAnchors()</span>, which dials any anchor that is not already connected and not banned. The effect is that a restarting node typically reconnects to its previous peers within seconds, well before the first periodic discovery tick fires at the 60-second mark.')}
${h2('/16 Subnet Diversity')}
${p('Anchor peers get you back online quickly, but they say nothing about whether your peer set is diverse. An attacker who controls a large IP block could fill your outbound slots with addresses from the same /16 subnet &mdash; once they own all your connections, they own what you see of the network. This is the classical eclipse attack.')}
${p('QubitCoin&rsquo;s discovery loop enforces a cap of two outbound connections per /16 subnet. Before picking the next peer to dial, it tallies the subnets already occupied by existing outbound connections:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">const subnetCounts = new Map&lt;string, number&gt;()<br>for (const peer of this.peers.values()) {<br>&nbsp;&nbsp;if (!peer.inbound) {<br>&nbsp;&nbsp;&nbsp;&nbsp;const subnet = getSubnet16(peer.address)<br>&nbsp;&nbsp;&nbsp;&nbsp;subnetCounts.set(subnet, (subnetCounts.get(subnet) ?? 0) + 1)<br>&nbsp;&nbsp;}<br>}<br>filtered = candidates.filter(<br>&nbsp;&nbsp;(a) =&gt; (subnetCounts.get(getSubnet16(a.host)) ?? 0) &lt; MAX_OUTBOUND_PER_SUBNET<br>)</span>')}
${p('The subnet is extracted by splitting the IPv4 address on dots and keeping the first two octets. IPv4-mapped addresses (<span class="font-mono text-xs text-qubit-400">::ffff:a.b.c.d</span>) are normalized into the same /16 buckets, while native IPv6 addresses fall back to the full address string as a key. If every known candidate already saturates its subnet, the filter is dropped and the node picks from all candidates rather than failing to connect at all &mdash; a reasonable degradation when the address book is small.')}
${h2('Why Inbound Connections Are Excluded')}
${p('The subnet cap only counts outbound connections. Inbound peers connect to you; you did not choose them. Counting inbound connections against the cap would let a well-connected peer inadvertently crowd out your ability to make new outbound contacts, and would give an attacker a way to degrade your outbound diversity by flooding you with inbound connections from a target subnet. Separating the two directions keeps the invariant clean: you control whom you dial, and the cap governs exactly that set.')}
${h2('Local Mode')}
${p('Running multiple nodes on a single machine for testing means all peers share the loopback address <span class="font-mono text-xs text-qubit-400">127.0.0.1</span>, which is both a private address and a single /16 subnet. The routability filter would reject it, and the subnet cap would block connections after the first two. Both checks are skipped when the server is started in local mode, so a multi-node test cluster on one machine works without special-casing every address comparison.')}
${h2('The Combined Effect')}
${p('Anchor persistence and subnet diversity address different failure modes. Anchors reduce cold-start time and avoid over-dependence on seed nodes &mdash; if the seeds go offline the node still knows a dozen peers from its last session. Subnet diversity limits how much of your peer budget one operator can consume, making it expensive to eclipse a node because the attacker must spread infrastructure across many /16 blocks rather than concentrating it in one. Together they make the network harder to partition and easier to rejoin &mdash; with about fifty lines of straightforward code.')}`,
};

export default post;
