import { type BlogPost, h2, p } from './types.js';

const post: BlogPost = {
  slug: 'mining-without-blocking-the-event-loop',
  title: 'Mining Without Blocking the Event Loop: Abortable Proof-of-Work in Node.js',
  date: '2026-05-24',
  tags: ['technical', 'engineering', 'development'],
  excerpt: 'Proof-of-work is a tight CPU loop. Node.js is single-threaded. We cooperatively schedule the hash search in small batches so the node stays responsive, restart instantly when a peer finds a block first, and auto-tune the batch size to the host it runs on.',
  content: () => `<h1 class="text-2xl font-bold mb-2">Mining Without Blocking the Event Loop: Abortable Proof-of-Work in Node.js</h1>
<p class="text-text-muted text-xs font-mono mb-8">2026-05-24</p>
${p('Proof-of-work mining is the most CPU-hungry thing a node does: hash a block header, check whether the digest is below the target, increment the nonce, repeat — billions of times. Node.js runs your JavaScript on a single thread. Put those two facts together and you have a problem: a naive <span class="font-mono text-xs text-qubit-400">while (true)</span> hash loop freezes everything else the node needs to do, including answering RPC calls, servicing peers, and — critically — noticing that someone else already mined the block you are still grinding on.')}
${h2('Why a Tight Loop Is the Wrong Default')}
${p('In a UTXO chain, mining is a race. Every node is searching for a nonce that satisfies the same difficulty target on top of the same chain tip. The moment any node wins, every other node should stop, accept the new block, and start over on top of it. A miner that keeps hashing against a stale tip is burning electricity to produce a block that will be orphaned the instant it is broadcast.')}
${p('So the mining loop has two jobs that pull in opposite directions. It must hash as fast as possible to be competitive, but it must also yield control frequently enough that the rest of the node can run — receive a peer block, abort the search, and feed it a fresh candidate. A blocking loop satisfies the first and fails the second.')}
${h2('Cooperative Scheduling With setTimeout')}
${p('The fix is to break the search into batches and hand control back to the event loop between them. <span class="font-mono text-xs text-qubit-400">mineBlockAsync</span> returns a Promise and drives an inner <span class="font-mono text-xs text-qubit-400">batch()</span> function that hashes a bounded number of nonces, then re-schedules itself:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">for (let i = 0; i &lt; batchSize; i++) {<br>&nbsp;&nbsp;block.header.nonce = nonce<br>&nbsp;&nbsp;const hash = computeBlockHash(block.header)<br>&nbsp;&nbsp;if (hashMeetsTarget(hash, target)) { finish(block); return }<br>&nbsp;&nbsp;nonce++<br>}<br>// ...tune batchSize...<br>setTimeout(batch, 0)</span>')}
${p('The choice of <span class="font-mono text-xs text-qubit-400">setTimeout(batch, 0)</span> over <span class="font-mono text-xs text-qubit-400">setImmediate</span> or a microtask is deliberate. A microtask (a resolved Promise) would re-run before the event loop gets a chance to process I/O at all — it would not actually yield. <span class="font-mono text-xs text-qubit-400">setTimeout</span> places the next batch behind pending timers and I/O callbacks, so a peer block that arrived on a socket gets handled between batches rather than after the whole search completes. It also avoids starving the loop under GC pressure, where <span class="font-mono text-xs text-qubit-400">setImmediate</span> chains can monopolise a tick.')}
${h2('Aborting Mid-Search')}
${p('Yielding is only half the story. When a peer block arrives, the node has to actually stop the in-flight search. QubitCoin wires this through the standard <span class="font-mono text-xs text-qubit-400">AbortController</span> / <span class="font-mono text-xs text-qubit-400">AbortSignal</span> API. The node holds one controller per mining round:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">this.miningAbort = new AbortController()<br>const block = await mineBlockAsync(candidate, this.miningAbort.signal, onProgress)</span>')}
${p('When <span class="font-mono text-xs text-qubit-400">receiveBlock</span> accepts a competing block, it calls <span class="font-mono text-xs text-qubit-400">this.miningAbort?.abort()</span>. The mining loop checks the signal in two places: once at the top of every batch, and again <em>inside</em> the hash loop every 256 nonces (<span class="font-mono text-xs text-qubit-400">ABORT_CHECK_INTERVAL</span>). The inner check matters because a single batch on a fast host can take tens of milliseconds — without it, an abort fired mid-batch would not take effect until the batch finished. Checking every 256 hashes makes cancellation feel instant while keeping the modulo test off the critical path of every single iteration.')}
${h2('Finishing Exactly Once')}
${p('A Promise can only resolve once, but this function has several exit paths: a block is found, the signal aborts, or the signal was already aborted before the first batch ran. To keep them from racing, every path funnels through a single guarded <span class="font-mono text-xs text-qubit-400">finish()</span>:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">const finish = (result) =&gt; {<br>&nbsp;&nbsp;if (finished) return<br>&nbsp;&nbsp;finished = true<br>&nbsp;&nbsp;signal?.removeEventListener(\'abort\', abort)<br>&nbsp;&nbsp;resolve(result)<br>}</span>')}
${p('The <span class="font-mono text-xs text-qubit-400">finished</span> flag makes <span class="font-mono text-xs text-qubit-400">finish()</span> idempotent, and removing the abort listener prevents a leak across the thousands of mining rounds a long-running node will perform. The listener is registered with <span class="font-mono text-xs text-qubit-400">{ once: true }</span> as a belt-and-suspenders guarantee, and the function bails immediately if <span class="font-mono text-xs text-qubit-400">signal.aborted</span> is already true on entry.')}
${h2('Auto-Tuning the Batch Size')}
${p('How many nonces should a batch hash before yielding? Too few and the scheduling overhead dominates; too many and the node becomes unresponsive between yields. The right number depends entirely on the host — a beefy server and a Raspberry Pi have wildly different hashrates. So the batch size is not a constant; it converges toward a target wall-clock duration of 25ms per batch using exponential smoothing:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">const idealBatch = Math.round(batchSize * TARGET_BATCH_MS / batchMs)<br>const ALPHA = 0.3<br>batchSize = clamp(MIN_BATCH_SIZE, MAX_BATCH_SIZE,<br>&nbsp;&nbsp;Math.round(ALPHA * idealBatch + (1 - ALPHA) * batchSize))</span>')}
${p('The smoothing factor <span class="font-mono text-xs text-qubit-400">ALPHA = 0.3</span> means each measurement nudges the batch size rather than overwriting it, so a single slow tick (a GC pause, say) does not whipsaw the loop. The search starts deliberately small — 2,048 nonces — so that on a slow host the very first abort check happens quickly instead of after a multi-second batch. From there it climbs toward whatever keeps each batch near 25ms, clamped between 256 and 100,000 nonces.')}
${h2('Restart, Not Resume')}
${p('When an abort fires, <span class="font-mono text-xs text-qubit-400">mineBlockAsync</span> resolves to <span class="font-mono text-xs text-qubit-400">null</span>, and the node&rsquo;s mining loop simply iterates again:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">if (block) {<br>&nbsp;&nbsp;// won the race: add it, clear mempool, broadcast<br>} else {<br>&nbsp;&nbsp;// aborted by receiveBlock → loop restarts with new tip<br>}</span>')}
${p('There is no attempt to resume the old search. That is correct by construction: once the tip changes, the previous candidate block is built on a stale parent and its entire nonce space is worthless. <span class="font-mono text-xs text-qubit-400">assembleCandidateBlock</span> runs fresh at the top of the loop, pulling the new tip, the current difficulty, and the latest mempool transactions. The same mechanism backs <span class="font-mono text-xs text-qubit-400">resetToHeight</span> during a reorg and <span class="font-mono text-xs text-qubit-400">stopMining</span> on shutdown — all three are just an <span class="font-mono text-xs text-qubit-400">abort()</span> against the same controller.')}
${h2('The Takeaway')}
${p('Single-threaded proof-of-work sounds like a contradiction, but it works as long as the loop is a good citizen: hash in bounded batches, yield through the macrotask queue, check for cancellation at two granularities, resolve exactly once, and let the host&rsquo;s own speed dictate the batch size. The result is a miner that competes hard while still answering RPC, gossiping with peers, and — most importantly — dropping a doomed search the instant the network moves on.')}`,
};

export default post;
