import { type BlogPost, h2, p } from './types.js';

const post: BlogPost = {
  slug: 'orphan-blocks-and-out-of-order-arrival',
  title: 'Orphan Blocks: Caching What You Can&rsquo;t Connect Yet',
  date: '2026-06-17',
  tags: ['technical', 'engineering', 'bitcoin'],
  excerpt: 'When a relayed block arrives before its parent, naively rejecting it would discard a valid tip. QubitCoin caches these orphan blocks in a bounded, expiring pool keyed by parent hash and reconnects the chain the moment the missing link shows up.',
  content: () => `<h1 class="text-2xl font-bold mb-2">Orphan Blocks: Caching What You Can&rsquo;t Connect Yet</h1>
<p class="text-text-muted text-xs font-mono mb-8">2026-06-17</p>
${p('In a peer-to-peer network, blocks do not always arrive in height order. A miner can broadcast a newly found block before their own node has finished propagating the previous one. A peer can relay the tip of a longer chain while you are still catching up. In all of these cases a node receives a block whose parent hash does not match anything in its local chain. The block is valid &mdash; it has good proof of work, a well-formed header, and correctly signed transactions &mdash; but it cannot be added yet because the chain it extends is not there.')}
${h2('The Wrong Answer')}
${p('The simplest response is to reject the block and let the peer resend it later. That is safe but wasteful. If the peer is honest, it is about to send the parent too, and retransmitting a block you already have is pure overhead. In a fast-propagating network where miners find blocks within seconds of each other, this kind of double-send under load can hurt propagation latency measurably.')}
${p('The opposite extreme &mdash; accepting any claimed-orphan unconditionally &mdash; is even worse. An attacker could flood your node with millions of structurally valid but parentless blocks, filling RAM until the process crashes. That makes orphan caching a classic denial-of-service surface.')}
${h2('OrphanBlockPool')}
${p('QubitCoin&rsquo;s <span class="font-mono text-xs text-qubit-400">OrphanBlockPool</span> in <span class="font-mono text-xs text-qubit-400">src/p2p/orphan-pool.ts</span> navigates between those two failure modes with three constraints:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">export class OrphanBlockPool {<br>&nbsp;&nbsp;constructor(<br>&nbsp;&nbsp;&nbsp;&nbsp;private readonly maxBlocks: number,<br>&nbsp;&nbsp;&nbsp;&nbsp;private readonly expiryMs: number,<br>&nbsp;&nbsp;) {}<br><br>&nbsp;&nbsp;add(block: Block, now = Date.now()): boolean {<br>&nbsp;&nbsp;&nbsp;&nbsp;if (computeBlockHash(block.header) !== block.hash) return false<br>&nbsp;&nbsp;&nbsp;&nbsp;if (!hashMeetsTarget(block.hash, block.header.target)) return false<br>&nbsp;&nbsp;&nbsp;&nbsp;this.expire(now)<br>&nbsp;&nbsp;&nbsp;&nbsp;if (this.orphanBlocks.size &gt;= this.maxBlocks) this.evictOldest()<br>&nbsp;&nbsp;&nbsp;&nbsp;const parentHash = block.header.previousHash<br>&nbsp;&nbsp;&nbsp;&nbsp;if (this.orphanBlocks.has(parentHash)) return false<br>&nbsp;&nbsp;&nbsp;&nbsp;this.orphanBlocks.set(parentHash, { block, receivedAt: now })<br>&nbsp;&nbsp;&nbsp;&nbsp;return true<br>&nbsp;&nbsp;}<br>}</span>')}
${p('<strong class="text-text-primary">Proof-of-work before caching.</strong> Before a block enters the pool, <span class="font-mono text-xs text-qubit-400">add()</span> recomputes the block hash and confirms it meets the claimed target. Work is the only Sybil-resistant resource in a proof-of-work chain. Requiring it means an attacker who wants to fill the pool must spend as much energy per fake orphan as a legitimate miner spends per real block.')}
${p('<strong class="text-text-primary">Hard size cap and expiry.</strong> The pool is configured with <span class="font-mono text-xs text-qubit-400">MAX_ORPHAN_BLOCKS = 50</span> and <span class="font-mono text-xs text-qubit-400">ORPHAN_EXPIRY_MS = 10 minutes</span>. Every <span class="font-mono text-xs text-qubit-400">add()</span> call first evicts entries older than the expiry window, then, if the pool is still full, removes the oldest remaining entry before inserting the new one. The cap is intentionally low: fifty orphans at average block size is a few megabytes at most, far below any memory budget that matters.')}
${p('<strong class="text-text-primary">Keyed by parent hash.</strong> The map key is the orphan&rsquo;s <span class="font-mono text-xs text-qubit-400">previousHash</span>, not its own hash. That design choice makes chain-connection lookups free &mdash; when a new block is accepted, the server just asks the pool for an orphan keyed by the accepted block&rsquo;s hash.')}
${h2('Connecting the Chain')}
${p('The connection loop in <span class="font-mono text-xs text-qubit-400">src/p2p/server.ts</span> runs every time a block is accepted:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">processOrphans(parentHash: string): number {<br>&nbsp;&nbsp;let added = 0<br>&nbsp;&nbsp;let currentHash = parentHash<br>&nbsp;&nbsp;let orphan = this.orphanBlocks.take(currentHash)<br>&nbsp;&nbsp;while (orphan &amp;&amp; added &lt; MAX_ORPHAN_BLOCKS) {<br>&nbsp;&nbsp;&nbsp;&nbsp;const result = this.node.receiveBlock(orphan.block)<br>&nbsp;&nbsp;&nbsp;&nbsp;if (result.success) {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;added++<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;currentHash = orphan.block.hash<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;orphan = this.orphanBlocks.take(currentHash)<br>&nbsp;&nbsp;&nbsp;&nbsp;} else { break }<br>&nbsp;&nbsp;}<br>&nbsp;&nbsp;return added<br>}</span>')}
${p('<span class="font-mono text-xs text-qubit-400">take()</span> atomically removes and returns an entry. The loop threads the chain forward: accept the orphan, use its hash as the next lookup key, try to find another orphan that was waiting for that block, and repeat. This handles runs of consecutive orphans in one shot &mdash; if blocks 101, 102, and 103 all arrived before block 100, the moment 100 is accepted the loop connects all three in sequence.')}
${h2('IBD vs. Relay: Two Different Paths')}
${p('Orphan caching only triggers for single-block relay messages. During Initial Block Download the server receives large batches of blocks from a peer. A "previous hash" rejection in that context does not mean "parent is missing" &mdash; it means the batch arrived out of order relative to a local fork, which is a different problem handled by the fork resolution path. Routing batch-IBD blocks into the orphan pool would bypass that logic and could lead to the node accepting a fork tip before the base of the fork is verified.')}
${p('The guard is a one-line check: if the incoming message contains more than one block, a "previous hash" error triggers fork resolution instead of orphan caching. Only single-block inbound messages check whether the parent is missing before deciding to cache.')}
${h2('What This Buys in Practice')}
${p('In a small network where block times are short relative to propagation delays, out-of-order arrival is common. A miner that finds two blocks in quick succession will broadcast the second before all peers have accepted the first. Without orphan caching, every peer would reject the second block, wait for a re-broadcast, and accept it on the second try. With the pool, the second block is cached on first arrival and connected automatically the moment the first one lands &mdash; no extra round-trip, no duplicate transfer.')}
${p('The pool capacity and expiry time are tuned to match that scenario. Fifty slots is enough to buffer a short burst of out-of-order blocks without giving an attacker meaningful storage leverage. Ten minutes is enough to survive a slow-propagating parent without keeping stale data around indefinitely. Both limits are conservative by design: the cost of an orphan that expires and must be retransmitted is a single extra network round-trip, which is far cheaper than the memory and CPU cost of an unbounded pool.')}`,
};

export default post;
