import { type BlogPost, h2, p } from './types.js';

const post: BlogPost = {
  slug: 'revalidating-the-mempool-after-a-reorg',
  title: 'Revalidating the Mempool After a Reorg: Keeping the Highest-Fee Spend',
  date: '2026-05-17',
  tags: ['technical', 'engineering', 'bitcoin'],
  excerpt: 'A chain reorganization rewrites which UTXOs exist, and that can leave the mempool holding transactions that conflict, double-spend, or reference outputs that no longer exist. We rebuild it in one deterministic pass: drop the invalid, then resolve every input conflict in favor of the higher fee density.',
  content: () => `<h1 class="text-2xl font-bold mb-2">Revalidating the Mempool After a Reorg: Keeping the Highest-Fee Spend</h1>
<p class="text-text-muted text-xs font-mono mb-8">2026-05-17</p>
${p('The mempool is a node&rsquo;s set of unconfirmed transactions, and it is only ever valid relative to a particular chain tip. Every transaction in it was admitted because its inputs pointed at unspent outputs that existed <em>at the time it arrived</em>. A reorg breaks that assumption all at once. When the node switches to a longer competing branch, blocks are disconnected and reconnected, and the UTXO set is rebuilt from scratch. Outputs that were spent on the old branch may be unspent again; outputs that were unspent may now be gone. The mempool, untouched, is suddenly full of transactions that may reference UTXOs that no longer exist, or that now conflict with each other.')}
${h2('Why a Naive Sweep Is Not Enough')}
${p('The obvious fix is to walk the mempool and drop anything whose inputs are missing from the new UTXO set. That handles the easy half — transactions stranded by the reorg get evicted. But it misses a subtler problem: two transactions that were never in conflict on the old branch can become double-spends on the new one. If a UTXO that was previously spent is now unspent again, the mempool might hold two independent transactions that both want to consume it. Both individually validate against the new UTXO set. Only one can ever be mined. A revalidation pass that keeps both leaves the mempool in an inconsistent state and lets the miner assemble a block that fails consensus.')}
${h2('Two Phases: Validity, Then Conflict Resolution')}
${p('QubitCoin&rsquo;s <span class="font-mono text-xs text-qubit-400">revalidate()</span> rebuilds the mempool in a single deterministic pass with two clearly separated phases. The first phase decides which transactions are even <em>eligible</em> — it re-runs full validation against the fresh UTXO set and confirms that every input still references a live output. The second phase takes the survivors and resolves any double-spends among them. Splitting it this way matters: you cannot pick a winner between two conflicting transactions until you know they are both otherwise valid.')}
${p('Claim transactions — the BTC&rarr;QBTC mints — are handled separately in the first phase. They do not consume ordinary UTXOs, so the test is different: a claim is dropped if its source Bitcoin address has already been claimed on the new branch, or if another claim for the same address is already present in the mempool. A small <span class="font-mono text-xs text-qubit-400">seenClaimKeys</span> set deduplicates them as the loop runs.')}
${h2('Resolving Conflicts by Fee Density')}
${p('Once the valid regular transactions are collected, each is tagged with its fee density — fee per byte — and the list is sorted descending:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">validRegulars.push({ id, tx, density: this.getFeeDensity(tx, utxoSet) })<br>// ...<br>validRegulars.sort((a, b) =&gt; b.density - a.density)</span>')}
${p('The conflict resolver then walks the sorted list and records every input it has committed to in a <span class="font-mono text-xs text-qubit-400">seenInputs</span> set. When a transaction wants an input that is already taken, it loses and is marked for removal; otherwise it claims its inputs and stays. Because the walk is in fee-density order, the first transaction to claim a contested UTXO is always the one paying the most per byte. This is the same incentive a miner has — given two spends of the same coin, take the one that pays better — applied at revalidation time so the mempool never advertises a transaction the miner would reject.')}
${p('Processing highest-fee-first also makes the outcome deterministic and independent of insertion order. Before this, the order transactions happened to be stored in could decide which survived a conflict; now the fee density decides, every time.')}
${h2('Rebuilding the Tracking State')}
${p('A mempool is not just a map of transactions — it carries derived indexes that have to stay in lockstep: the running byte total used for size limits, the set of UTXOs already claimed by pending transactions, and the set of pending BTC claim addresses. After eviction these are stale, so the final step clears every cache and rebuilds the tracking sets from the surviving transactions in one loop:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">this.feeDensityCache.clear()<br>this.claimedUTXOs.clear()<br>this.pendingBtcClaims.clear()<br>for (const tx of this.transactions.values()) {<br>&nbsp;&nbsp;// re-add claim addresses or input keys<br>}</span>')}
${p('Rebuilding wholesale rather than incrementally patching the indexes is the safer choice here. After a reorg the cheapest source of truth is the surviving transaction map itself, and deriving everything else from it removes any chance of an index drifting out of sync with the set it is supposed to describe.')}
${h2('The Same Order, On the Way Out')}
${p('The fee-density ordering that resolves conflicts on revalidation is the same one the node uses when it hands transactions to the miner for block assembly: claims first, then regular transactions by fee per byte, descending. Keeping a single notion of &ldquo;which transaction is more valuable&rdquo; across both paths means a transaction that survives revalidation is exactly the one the miner would have picked anyway — there is no second, contradictory ranking to reconcile.')}
${h2('The Takeaway')}
${p('A reorg is the one moment a mempool&rsquo;s core assumption — that its transactions match the current UTXO set — is guaranteed to be wrong. Recovering correctly means more than dropping the stranded transactions: it means resolving the double-spends the reorg created, and doing it the way the network would. Validate first, resolve conflicts by fee density second, rebuild the indexes from the survivors, and the mempool comes out the far side of a chain reorganization consistent, deterministic, and ready to feed the miner.')}`,
};

export default post;
