import { type BlogPost, h2, p, steps } from './types.js';

const post: BlogPost = {
  slug: 'trusting-proxies-without-breaking-rpc-rate-limits',
  title: 'Trusting Proxies Without Breaking RPC Rate Limits',
  date: '2026-06-05',
  tags: ['technical', 'engineering', 'bitcoin'],
  excerpt: 'Per-IP rate limiting only works if the server identifies the right IP. QubitCoin now makes proxy trust an explicit RPC setting so reverse-proxied deployments can rate-limit real clients, while directly exposed nodes ignore spoofed forwarded headers.',
  content: () => `<h1 class="text-2xl font-bold mb-2">Trusting Proxies Without Breaking RPC Rate Limits</h1>
<p class="text-text-muted text-xs font-mono mb-8">2026-06-05</p>
${p('QubitCoin rate-limits every <span class="font-mono text-xs text-qubit-400">/api/v1/*</span> route by client IP. That sounds straightforward until you put the RPC server behind nginx, Caddy, HAProxy, or an ingress controller. The TCP peer qbtcd sees is then the proxy, not the original caller. If rate limiting keys off the proxy address, every client gets collapsed into one bucket. If it blindly trusts forwarded headers from anyone, a directly connected attacker can choose a fresh fake IP for every request and bypass the limiter entirely. The recent RPC change makes that trust decision explicit.')}
${h2('The Real Problem Is Not the Limiter')}
${p('The limiter itself is simple: GET and POST requests have separate buckets, and each bucket is keyed by <span class="font-mono text-xs text-qubit-400">req.ip</span>. The subtlety is that <span class="font-mono text-xs text-qubit-400">req.ip</span> is only meaningful if Express knows when to trust <span class="font-mono text-xs text-qubit-400">X-Forwarded-For</span>. That behavior is controlled by <span class="font-mono text-xs text-qubit-400">app.set(&#39;trust proxy&#39;, ...)</span>, which means the security boundary for rate limiting is really proxy configuration, not the sliding-window counter.')}
${p('QubitCoin surfaces that boundary as a daemon option: <span class="font-mono text-xs text-qubit-400">--rpc-trust-proxy</span>. The RPC server passes the parsed value straight into Express, so the same setting determines which upstream hops may supply the client address for rate limiting, logging, and any future IP-based policy.')}
${h2('Safe by Default for Common Reverse Proxies')}
${p('The default trust set is <span class="font-mono text-xs text-qubit-400">loopback,linklocal,uniquelocal</span>. In practice that means qbtcd will trust forwarded headers when the immediate upstream peer is a same-host proxy or a private-network ingress, but not from arbitrary public clients. This matches the common deployment shape where nginx listens publicly and proxies to qbtcd over <span class="font-mono text-xs text-qubit-400">127.0.0.1</span> or a private container network.')}
${p('That default matters because a reverse-proxied node should still rate-limit the real caller, not the proxy process. With trusted local proxies, one client at <span class="font-mono text-xs text-qubit-400">198.51.100.10</span> and another at <span class="font-mono text-xs text-qubit-400">203.0.113.77</span> land in different buckets even though qbtcd receives both requests from the same local upstream hop.')}
${h2('Explicit Off Means Spoofing Does Not Work')}
${p('The other half of the design is just as important: operators can disable forwarded-header trust entirely with <span class="font-mono text-xs text-qubit-400">--rpc-trust-proxy=false</span>. In that mode the server ignores <span class="font-mono text-xs text-qubit-400">X-Forwarded-For</span> and uses the socket peer address only. A directly exposed RPC listener should run that way, because otherwise any client can rotate fake header values and escape a per-IP limiter for free.')}
${p('The test coverage makes this concrete. One test sends one hundred invalid POSTs with <span class="font-mono text-xs text-qubit-400">X-Forwarded-For: 198.51.100.10</span>, then a final request with <span class="font-mono text-xs text-qubit-400">X-Forwarded-For: 203.0.113.77</span>. When trust is disabled, the last request is still rejected with HTTP 429 because all traffic came from the same real socket peer. Spoofing the header does not buy a new bucket.')}
${h2('Hop Counts and Proxy Lists Are Different Tools')}
${p('Express accepts several proxy trust modes, and QubitCoin preserves them instead of inventing a custom abstraction. Boolean values are explicit on/off. Comma-separated labels or CIDRs let operators trust specific networks. Positive integers trust a fixed number of proxy hops.')}
${steps([
  '<span class="font-mono text-xs text-qubit-400">--rpc-trust-proxy=loopback</span> trusts only same-host proxies.',
  '<span class="font-mono text-xs text-qubit-400">--rpc-trust-proxy=10.0.0.0/8,192.168.0.0/16</span> trusts explicit private networks.',
  '<span class="font-mono text-xs text-qubit-400">--rpc-trust-proxy=1</span> trusts exactly one upstream proxy hop.',
  '<span class="font-mono text-xs text-qubit-400">--rpc-trust-proxy=2</span> trusts two hops, which is useful when a public ingress sits in front of another internal proxy.',
])}
${p('The parser is intentionally strict about numeric-looking values. Positive integers are treated as hop counts. <span class="font-mono text-xs text-qubit-400">0</span>, <span class="font-mono text-xs text-qubit-400">false</span>, and <span class="font-mono text-xs text-qubit-400">off</span> all mean "do not trust forwarded headers." Values like <span class="font-mono text-xs text-qubit-400">-1</span> or <span class="font-mono text-xs text-qubit-400">1.5</span> are rejected at startup instead of being quietly misread as proxy labels. That is the right failure mode for a security-sensitive configuration knob.')}
${h2('Why Bind Address Is Not a Trust Signal')}
${p('One easy mistake is to assume that binding the RPC server to <span class="font-mono text-xs text-qubit-400">127.0.0.1</span> makes proxy trust safe, or that binding to <span class="font-mono text-xs text-qubit-400">0.0.0.0</span> means it must be unsafe. The code now avoids that inference completely. Bind address controls where the socket listens; it does not tell qbtcd whether the peer on the other end is a trusted reverse proxy, a load balancer, or a raw client.')}
${p('That separation is subtle but important operationally. A public-facing listener can still be safe if only trusted infrastructure can reach it. A loopback listener can still be misconfigured if the upstream proxy chain is longer than expected or if forwarded headers are accepted too broadly. Keeping bind and trust as two different settings forces the operator to state both assumptions clearly.')}
${h2('What the Tests Actually Prove')}
${p('The recent RPC tests cover four cases that matter in production: direct clients hitting the POST limiter, spoofed <span class="font-mono text-xs text-qubit-400">X-Forwarded-For</span> headers being ignored when trust is off, trusted loopback proxies preserving distinct client buckets, and numeric hop counts honoring the real client address across a multi-proxy chain without trusting extra hops.')}
${p('That last case is the one that usually gets hand-waved in small projects. It is easy to support one reverse proxy. It is harder to prove that a two-hop chain still attributes requests correctly without turning "trust one hop" into "trust any string the caller sends." QubitCoin now tests that path explicitly by forwarding through two local proxy processes and confirming that different client IPs still rate-limit independently.')}
${h2('The Broader Rule')}
${p('Per-IP rate limiting is only as good as the function that decides what an IP is. In a reverse-proxied deployment, that function is a trust policy. QubitCoin now makes that policy explicit, strict, and test-covered: trust local or configured proxies when they are real, ignore forwarded headers when they are not, and reject ambiguous configuration values before the server starts. That is not glamorous work, but it is the difference between a limiter that looks correct in code review and one that actually holds up in production.')}`,
};

export default post;
