import { type BlogPost, h2, p } from './types.js';

const post: BlogPost = {
  slug: 'validating-p2p-messages-at-the-wire',
  title: 'Validating P2P Messages at the Wire: Shape Checks Before Logic',
  date: '2026-05-24',
  tags: ['technical', 'engineering', 'bitcoin'],
  excerpt: 'A peer can send any bytes it likes. QubitCoin&rsquo;s frame decoder treats every decoded message as hostile until proven otherwise — rejecting unknown types and malformed payloads at the decode boundary so the rest of the node never has to ask whether the shape it received is the shape it expected.',
  content: () => `<h1 class="text-2xl font-bold mb-2">Validating P2P Messages at the Wire: Shape Checks Before Logic</h1>
<p class="text-text-muted text-xs font-mono mb-8">2026-05-24</p>
${p('Every byte a node reads from a peer is attacker-controlled. The P2P wire format is simple — a 4-byte big-endian length prefix followed by a JSON payload — but <span class="font-mono text-xs text-qubit-400">JSON.parse</span> will happily hand back anything: a number, a string, an object with a <span class="font-mono text-xs text-qubit-400">type</span> field that names a message the node has never heard of, or a <span class="font-mono text-xs text-qubit-400">tx</span> message whose payload is the literal <span class="font-mono text-xs text-qubit-400">null</span>. If that value flows straight into the message handlers, every handler becomes responsible for re-checking the shape of its own input, and the first one that forgets is a crash or worse.')}
${h2('A Single Choke Point')}
${p('QubitCoin pushes all of that doubt into one function. The frame decoder, <span class="font-mono text-xs text-qubit-400">decodeMessages()</span>, reads a length prefix, slices out exactly that many bytes, parses the JSON, and immediately passes the result to <span class="font-mono text-xs text-qubit-400">validateDecodedMessage()</span> before the message is ever returned to the caller:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">const json = buffer.toString(&#39;utf-8&#39;, offset + 4, offset + 4 + length)<br>const msg = validateDecodedMessage(JSON.parse(json))<br>messages.push(msg)</span>')}
${p('Because nothing leaves the decoder without passing through that validator, the rest of the node gets to assume that a <span class="font-mono text-xs text-qubit-400">Message</span> is well-formed. The type is one of the fourteen the protocol defines, and a payload that is supposed to be an object is an object. The trust boundary is the decoder, and it is the only place that boundary exists.')}
${h2('Three Questions, In Order')}
${p('Validation asks three things, and the order matters because each step makes the next one safe. First: is the decoded value even an object? A peer can frame a bare array or a number as valid JSON, so the check rejects anything that is not a non-null, non-array object before touching its fields.')}
${p('Second: does it carry a known type? The <span class="font-mono text-xs text-qubit-400">type</span> field must be a non-empty string and must be a member of <span class="font-mono text-xs text-qubit-400">VALID_MESSAGE_TYPES</span>, a frozen set built once at module load. Membership is an O(1) set lookup, not a chain of comparisons — an unknown type like <span class="font-mono text-xs text-qubit-400">&quot;exec&quot;</span> is rejected with the same single operation that admits <span class="font-mono text-xs text-qubit-400">&quot;ping&quot;</span>:')}
${p('<span class="font-mono text-xs text-qubit-400 block bg-surface rounded p-3 mb-2">if (!isValidMessageType(type)) {<br>&nbsp;&nbsp;throw new Error(\`Invalid message type: \${type}\`)<br>}</span>')}
${p('Third: if this type is supposed to carry a structured payload, is the payload shaped correctly? Not every message has a payload — <span class="font-mono text-xs text-qubit-400">ping</span>, <span class="font-mono text-xs text-qubit-400">pong</span>, <span class="font-mono text-xs text-qubit-400">verack</span>, and <span class="font-mono text-xs text-qubit-400">getaddr</span> are bare signals — so a second set, <span class="font-mono text-xs text-qubit-400">OBJECT_PAYLOAD_TYPES</span>, marks the ones that must arrive with an object payload. Only those run the per-type structural check.')}
${h2('Shape, Not Semantics')}
${p('The per-type checks in <span class="font-mono text-xs text-qubit-400">validateStructuredPayload()</span> are deliberately shallow. A <span class="font-mono text-xs text-qubit-400">blocks</span> message must have a <span class="font-mono text-xs text-qubit-400">blocks</span> array; a <span class="font-mono text-xs text-qubit-400">tx</span> message must have a <span class="font-mono text-xs text-qubit-400">tx</span> object; an <span class="font-mono text-xs text-qubit-400">inv</span> or <span class="font-mono text-xs text-qubit-400">getdata</span> must have <span class="font-mono text-xs text-qubit-400">type</span> and <span class="font-mono text-xs text-qubit-400">hash</span> strings. That is all the decoder asserts. It does not verify that a block&rsquo;s proof-of-work is valid, that a transaction&rsquo;s signatures verify, or that a hash refers to anything that exists.')}
${p('That restraint is intentional. Mixing wire-shape validation with consensus validation would force the decoder to import the entire chain and crypto stack and would blur the line between &ldquo;this message is garbage&rdquo; and &ldquo;this message is well-formed but invalid.&rdquo; Those are different failures with different responses: a malformed frame is a protocol violation that should sever the connection, while a well-formed-but-invalid block is a misbehavior the peer-scoring system penalizes and tallies. Keeping the decoder to shape-checks-only means the layers above it always know which kind of bad input they are looking at.')}
${h2('Why an Array Payload Was the Bug Worth Fixing')}
${p('The subtle cases are the ones that pass a casual check. In JavaScript, <span class="font-mono text-xs text-qubit-400">typeof [] === &quot;object&quot;</span> and <span class="font-mono text-xs text-qubit-400">typeof null === &quot;object&quot;</span>, so a naive <span class="font-mono text-xs text-qubit-400">typeof payload === &quot;object&quot;</span> guard lets both an array and a null slip through as if they were a real payload object. The handler then reads <span class="font-mono text-xs text-qubit-400">payload.blocks</span> off an array and gets <span class="font-mono text-xs text-qubit-400">undefined</span>, or dereferences <span class="font-mono text-xs text-qubit-400">null</span> and throws deep inside logic that assumed its input was sound. QubitCoin&rsquo;s <span class="font-mono text-xs text-qubit-400">isMessageObject()</span> helper closes both holes explicitly — non-null, non-array, object — and every payload check routes through it.')}
${h2('Fail Closed, Frame by Frame')}
${p('The decoder runs a loop, pulling complete frames out of an accumulating buffer one at a time. A thrown validation error is not caught and skipped — it propagates out of <span class="font-mono text-xs text-qubit-400">decodeMessages()</span>, and the peer connection that produced the bad frame is the one that pays for it. There is no &ldquo;skip this message and keep reading the stream&rdquo; path, because a peer that sent one malformed frame has already proven it is either buggy or hostile, and continuing to parse its byte stream only invites the next malformed frame. Length checks live in the same loop: a zero-length frame and a frame claiming more than the 5 MB <span class="font-mono text-xs text-qubit-400">MAX_MESSAGE_SIZE</span> are both rejected before a single byte of their body is read.')}
${h2('The Takeaway')}
${p('Validating P2P messages at the wire is not glamorous, but it is the difference between a node that assumes its inputs and a node that proves them. By concentrating every structural check into the decode boundary — known type, correct payload shape, no array-or-null masquerading as an object — QubitCoin lets every layer above the wire reason about messages instead of re-validating them, and keeps the question &ldquo;is this even the right shape?&rdquo; firmly separated from &ldquo;is this consensus-valid?&rdquo; The peer can send any bytes it likes; only well-formed messages make it past the door.')}`,
};

export default post;
